# Generated by Django 4.2.11 on 2024-05-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0002_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
