# Generated by Django 4.2.11 on 2024-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0003_delete_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('session', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=9)),
                ('week_type', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=4)),
                ('food_item', models.CharField(max_length=255)),
            ],
        ),
    ]
