# Generated by Django 4.2.11 on 2024-05-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0004_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_update_database', 'Can update database')]},
        ),
    ]
