# Generated by Django 4.2.11 on 2024-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0005_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_update_database', 'Can update mess items database')]},
        ),
    ]
