# Generated by Django 4.2.11 on 2024-05-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0006_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_update_database1', 'Awesome User can update mess items database')]},
        ),
    ]
