# Generated by Django 4.2.11 on 2024-05-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messwebsite', '0008_remove_review_food_item_delete_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messwebsite.menuitem'),
        ),
    ]
